<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="festival">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="venues"/>
                <xs:element ref="performers"/>
                <xs:element ref="events"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="location" type="xs:string" use="required"/>
            <xs:attribute name="year" type="xs:gYear" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="venues">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="venue" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="capacity">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="100"/>
                                        <xs:maxInclusive value="100000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="performers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="performer" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                        <xs:attribute name="type" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="music"/>
                                    <xs:enumeration value="dance"/>
                                    <xs:enumeration value="show"/>
                                    <xs:enumeration value="competition"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="genre" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="event" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="performer" type="xs:IDREF" use="required"/>
                        <xs:attribute name="venue" type="xs:IDREF" use="required"/>
                        <xs:attribute name="start" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="([01][0-9]|2[0-3]):[0-5][0-9]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="end" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="([01][0-9]|2[0-3]):[0-5][0-9]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>